# Generated by Django 4.1.13 on 2024-09-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urls',
            fields=[
                ('long_url', models.URLField()),
                ('key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('short_url', models.URLField()),
                ('impression', models.IntegerField(default=0)),
            ],
        ),
    ]
